git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

language: php

notifications:
    email: false

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - 'nightly'

before_install:
    - (phpenv config-rm xdebug.ini || exit 0)
    - composer self-update

install:
    - composer require --dev phpunit/phpunit squizlabs/php_codesniffer

script:
    - vendor/bin/phpcs --report-full --standard=PSR2 src tests
    - vendor/bin/phpunit -c tests/phpunit.xml
